# Generated by Django 4.2.1 on 2023-05-21 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=1212, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default=11, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
