# Generated by Django 4.2.1 on 2023-05-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_book_book_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editor',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='editor_name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='editor_surname',
            new_name='author_surname',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_editor',
            new_name='book_author',
        ),
    ]
