# Generated by Django 4.2.1 on 2023-05-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_book_book_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_created',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
