# Generated by Django 4.2.1 on 2023-05-22 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_book_book_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_created',
        ),
    ]
